# Jekyll configuration for GitHub Pages
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

title: IT Passport App
description: IT Passport exam preparation application

# GitHub Pages specific settings
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - README.md
  - .gitignore
  - 250718c/
  - 250718test/
  - 250720test/
